# Generated by Django 4.0.4 on 2022-12-01 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_date_of_crime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Date_of_crime',
            new_name='Date_of_blog',
        ),
    ]
